/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JekyllPostGenerator;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

public class App {
  public static void main(String[] args) throws IOException{
    // TODO code application logic here
    BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
    Date date = new Date();
    
    DateFormat dateFormat1 = new SimpleDateFormat("yyyy-MM-dd");
    DateFormat dateFormat2 = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    //Enter name of article
    System.out.println("----Jekyll Post Generator----");
    System.out.print("Enter post name: ");
    String postName = reader.readLine();
    String postNameInFileName = postName.replace(" ", "-");
    String postFileName = dateFormat1.format(date) + "-" + postNameInFileName + ".md";

    //Check if file name is exist or not
    File file = new File(postFileName);
    if (file.exists() == true) {
      System.out.println("File name \"" + postFileName + "\" did exitst. Becareful");
    } else {
      //Create new file 
      try ( PrintWriter writer = new PrintWriter(file)) {
        writer.println("---");
        writer.println("layout: post");
        writer.println("title: \"" + postName + "\"");
        writer.println("date: " + dateFormat2.format(date));
        writer.println("update: ");
        writer.println("location: ");
        writer.println("tags: ");
        writer.println("categories: ");
        writer.println("seo_description: ");
        writer.println("seo_image: ");
        writer.println("comments: true");
        writer.println("---");
        writer.close();
        System.out.println("File named \"" + postFileName + "\" generated.");
        System.out.println("Please check the following directory: " + System.getProperty("user.dir"));
      } catch (FileNotFoundException ex) {
        System.out.println(ex);
      }
    }
  }
}
